trigger:
- master

pool:
  name: UbuntuPool

steps:
- checkout: self

- task: SonarQubePrepare@7
  inputs:
    SonarQube: 'SonarQubeConnection'
    scannerMode: 'Other'
    extraProperties: |
      sonar.projectKey=hello-world1
      sonar.projectName=hello-world1

- script: |
    mvn clean package sonar:sonar
  displayName: "Build and Sonar Scan"

- task: SonarQubePublish@7
  inputs:
    pollingTimeoutSec: '300'